version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: golift_postgres_prod
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d/
    networks:
      - golift_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 5s
      retries: 5

  migration:
    image: migrate/migrate
    container_name: go_lift_migration
    restart: "no"
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations
    command:
      - -path=/migrations
      - -database=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      - up
    networks:
      - golift_network
    depends_on:
      postgres:
        condition: service_healthy

  workout-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: services/workout-service
    container_name: golift_workout_service
    restart: always
    env_file:
      - .env
    environment:
      - PORT=${WORKOUT_GRPC_PORT}
    networks:
      - golift_network
    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

  tg-bot-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: services/tg-bot-gateway
    container_name: golift_gateway
    restart: always
    ports:
      - "${TG_HTTP_PORT}:${TG_HTTP_PORT}"
    env_file:
      - .env
    environment:
      - PORT=${TG_HTTP_PORT}
      - HTTP_PORT=${TG_HTTP_PORT}
    networks:
      - golift_network
    depends_on:
      - workout-service

networks:
  golift_network:
    driver: bridge

volumes:
  pgdata_prod: