// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/proto/workout/v1/workout.proto

package workoutv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkoutService_Init_FullMethodName                  = "/workout.v1.WorkoutService/Init"
	WorkoutService_GetMuscleGroups_FullMethodName       = "/workout.v1.WorkoutService/GetMuscleGroups"
	WorkoutService_GetExercises_FullMethodName          = "/workout.v1.WorkoutService/GetExercises"
	WorkoutService_StartWorkoutSession_FullMethodName   = "/workout.v1.WorkoutService/StartWorkoutSession"
	WorkoutService_FinishWorkoutSession_FullMethodName  = "/workout.v1.WorkoutService/FinishWorkoutSession"
	WorkoutService_LogWorkoutSet_FullMethodName         = "/workout.v1.WorkoutService/LogWorkoutSet"
	WorkoutService_GetCompletedExercises_FullMethodName = "/workout.v1.WorkoutService/GetCompletedExercises"
	WorkoutService_GetTrainingDays_FullMethodName       = "/workout.v1.WorkoutService/GetTrainingDays"
	WorkoutService_GetWorkoutsForDay_FullMethodName     = "/workout.v1.WorkoutService/GetWorkoutsForDay"
	WorkoutService_CreateTemplate_FullMethodName        = "/workout.v1.WorkoutService/CreateTemplate"
)

// WorkoutServiceClient is the client API for WorkoutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkoutServiceClient interface {
	// Инициализация
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	// Получение списка мышечных групп
	GetMuscleGroups(ctx context.Context, in *GetMuscleGroupsRequest, opts ...grpc.CallOption) (*GetMuscleGroupsResponse, error)
	// Справочники упражнений
	GetExercises(ctx context.Context, in *GetExercisesRequest, opts ...grpc.CallOption) (*GetExercisesResponse, error)
	// Старт тренировочной сессии
	StartWorkoutSession(ctx context.Context, in *StartWorkoutSessionRequest, opts ...grpc.CallOption) (*StartWorkoutSessionResponse, error)
	// Завершение тренировочной сессии
	FinishWorkoutSession(ctx context.Context, in *FinishWorkoutSessionRequest, opts ...grpc.CallOption) (*FinishWorkoutSessionResponse, error)
	// Сохранить/обновить выполненное упражнение
	LogWorkoutSet(ctx context.Context, in *LogSetRequest, opts ...grpc.CallOption) (*LogSetResponse, error)
	// Получить список выполненных упражнений определенного вида в активной сессии
	GetCompletedExercises(ctx context.Context, in *GetCompletedExercisesRequest, opts ...grpc.CallOption) (*GetCompletedExercisesResponse, error)
	// Получить список тренировочных дней
	GetTrainingDays(ctx context.Context, in *GetTrainingDaysRequest, opts ...grpc.CallOption) (*GetTrainingDaysResponse, error)
	// Получить выполненные упражнения за день
	GetWorkoutsForDay(ctx context.Context, in *GetWorkoutsForDayRequest, opts ...grpc.CallOption) (*GetWorkoutsForDayResponse, error)
	// Создание шаблона тренировки
	CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*CreateTemplateResponse, error)
}

type workoutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkoutServiceClient(cc grpc.ClientConnInterface) WorkoutServiceClient {
	return &workoutServiceClient{cc}
}

func (c *workoutServiceClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, WorkoutService_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) GetMuscleGroups(ctx context.Context, in *GetMuscleGroupsRequest, opts ...grpc.CallOption) (*GetMuscleGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMuscleGroupsResponse)
	err := c.cc.Invoke(ctx, WorkoutService_GetMuscleGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) GetExercises(ctx context.Context, in *GetExercisesRequest, opts ...grpc.CallOption) (*GetExercisesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExercisesResponse)
	err := c.cc.Invoke(ctx, WorkoutService_GetExercises_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) StartWorkoutSession(ctx context.Context, in *StartWorkoutSessionRequest, opts ...grpc.CallOption) (*StartWorkoutSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartWorkoutSessionResponse)
	err := c.cc.Invoke(ctx, WorkoutService_StartWorkoutSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) FinishWorkoutSession(ctx context.Context, in *FinishWorkoutSessionRequest, opts ...grpc.CallOption) (*FinishWorkoutSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishWorkoutSessionResponse)
	err := c.cc.Invoke(ctx, WorkoutService_FinishWorkoutSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) LogWorkoutSet(ctx context.Context, in *LogSetRequest, opts ...grpc.CallOption) (*LogSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogSetResponse)
	err := c.cc.Invoke(ctx, WorkoutService_LogWorkoutSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) GetCompletedExercises(ctx context.Context, in *GetCompletedExercisesRequest, opts ...grpc.CallOption) (*GetCompletedExercisesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCompletedExercisesResponse)
	err := c.cc.Invoke(ctx, WorkoutService_GetCompletedExercises_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) GetTrainingDays(ctx context.Context, in *GetTrainingDaysRequest, opts ...grpc.CallOption) (*GetTrainingDaysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrainingDaysResponse)
	err := c.cc.Invoke(ctx, WorkoutService_GetTrainingDays_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) GetWorkoutsForDay(ctx context.Context, in *GetWorkoutsForDayRequest, opts ...grpc.CallOption) (*GetWorkoutsForDayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkoutsForDayResponse)
	err := c.cc.Invoke(ctx, WorkoutService_GetWorkoutsForDay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*CreateTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTemplateResponse)
	err := c.cc.Invoke(ctx, WorkoutService_CreateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkoutServiceServer is the server API for WorkoutService service.
// All implementations must embed UnimplementedWorkoutServiceServer
// for forward compatibility.
type WorkoutServiceServer interface {
	// Инициализация
	Init(context.Context, *InitRequest) (*InitResponse, error)
	// Получение списка мышечных групп
	GetMuscleGroups(context.Context, *GetMuscleGroupsRequest) (*GetMuscleGroupsResponse, error)
	// Справочники упражнений
	GetExercises(context.Context, *GetExercisesRequest) (*GetExercisesResponse, error)
	// Старт тренировочной сессии
	StartWorkoutSession(context.Context, *StartWorkoutSessionRequest) (*StartWorkoutSessionResponse, error)
	// Завершение тренировочной сессии
	FinishWorkoutSession(context.Context, *FinishWorkoutSessionRequest) (*FinishWorkoutSessionResponse, error)
	// Сохранить/обновить выполненное упражнение
	LogWorkoutSet(context.Context, *LogSetRequest) (*LogSetResponse, error)
	// Получить список выполненных упражнений определенного вида в активной сессии
	GetCompletedExercises(context.Context, *GetCompletedExercisesRequest) (*GetCompletedExercisesResponse, error)
	// Получить список тренировочных дней
	GetTrainingDays(context.Context, *GetTrainingDaysRequest) (*GetTrainingDaysResponse, error)
	// Получить выполненные упражнения за день
	GetWorkoutsForDay(context.Context, *GetWorkoutsForDayRequest) (*GetWorkoutsForDayResponse, error)
	// Создание шаблона тренировки
	CreateTemplate(context.Context, *CreateTemplateRequest) (*CreateTemplateResponse, error)
	mustEmbedUnimplementedWorkoutServiceServer()
}

// UnimplementedWorkoutServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkoutServiceServer struct{}

func (UnimplementedWorkoutServiceServer) Init(context.Context, *InitRequest) (*InitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedWorkoutServiceServer) GetMuscleGroups(context.Context, *GetMuscleGroupsRequest) (*GetMuscleGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMuscleGroups not implemented")
}
func (UnimplementedWorkoutServiceServer) GetExercises(context.Context, *GetExercisesRequest) (*GetExercisesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExercises not implemented")
}
func (UnimplementedWorkoutServiceServer) StartWorkoutSession(context.Context, *StartWorkoutSessionRequest) (*StartWorkoutSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartWorkoutSession not implemented")
}
func (UnimplementedWorkoutServiceServer) FinishWorkoutSession(context.Context, *FinishWorkoutSessionRequest) (*FinishWorkoutSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinishWorkoutSession not implemented")
}
func (UnimplementedWorkoutServiceServer) LogWorkoutSet(context.Context, *LogSetRequest) (*LogSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LogWorkoutSet not implemented")
}
func (UnimplementedWorkoutServiceServer) GetCompletedExercises(context.Context, *GetCompletedExercisesRequest) (*GetCompletedExercisesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompletedExercises not implemented")
}
func (UnimplementedWorkoutServiceServer) GetTrainingDays(context.Context, *GetTrainingDaysRequest) (*GetTrainingDaysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrainingDays not implemented")
}
func (UnimplementedWorkoutServiceServer) GetWorkoutsForDay(context.Context, *GetWorkoutsForDayRequest) (*GetWorkoutsForDayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkoutsForDay not implemented")
}
func (UnimplementedWorkoutServiceServer) CreateTemplate(context.Context, *CreateTemplateRequest) (*CreateTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTemplate not implemented")
}
func (UnimplementedWorkoutServiceServer) mustEmbedUnimplementedWorkoutServiceServer() {}
func (UnimplementedWorkoutServiceServer) testEmbeddedByValue()                        {}

// UnsafeWorkoutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkoutServiceServer will
// result in compilation errors.
type UnsafeWorkoutServiceServer interface {
	mustEmbedUnimplementedWorkoutServiceServer()
}

func RegisterWorkoutServiceServer(s grpc.ServiceRegistrar, srv WorkoutServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkoutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkoutService_ServiceDesc, srv)
}

func _WorkoutService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_GetMuscleGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMuscleGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).GetMuscleGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_GetMuscleGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).GetMuscleGroups(ctx, req.(*GetMuscleGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_GetExercises_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExercisesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).GetExercises(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_GetExercises_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).GetExercises(ctx, req.(*GetExercisesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_StartWorkoutSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWorkoutSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).StartWorkoutSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_StartWorkoutSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).StartWorkoutSession(ctx, req.(*StartWorkoutSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_FinishWorkoutSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishWorkoutSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).FinishWorkoutSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_FinishWorkoutSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).FinishWorkoutSession(ctx, req.(*FinishWorkoutSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_LogWorkoutSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).LogWorkoutSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_LogWorkoutSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).LogWorkoutSet(ctx, req.(*LogSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_GetCompletedExercises_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompletedExercisesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).GetCompletedExercises(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_GetCompletedExercises_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).GetCompletedExercises(ctx, req.(*GetCompletedExercisesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_GetTrainingDays_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrainingDaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).GetTrainingDays(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_GetTrainingDays_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).GetTrainingDays(ctx, req.(*GetTrainingDaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_GetWorkoutsForDay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkoutsForDayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).GetWorkoutsForDay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_GetWorkoutsForDay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).GetWorkoutsForDay(ctx, req.(*GetWorkoutsForDayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_CreateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).CreateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_CreateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).CreateTemplate(ctx, req.(*CreateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkoutService_ServiceDesc is the grpc.ServiceDesc for WorkoutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkoutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workout.v1.WorkoutService",
	HandlerType: (*WorkoutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _WorkoutService_Init_Handler,
		},
		{
			MethodName: "GetMuscleGroups",
			Handler:    _WorkoutService_GetMuscleGroups_Handler,
		},
		{
			MethodName: "GetExercises",
			Handler:    _WorkoutService_GetExercises_Handler,
		},
		{
			MethodName: "StartWorkoutSession",
			Handler:    _WorkoutService_StartWorkoutSession_Handler,
		},
		{
			MethodName: "FinishWorkoutSession",
			Handler:    _WorkoutService_FinishWorkoutSession_Handler,
		},
		{
			MethodName: "LogWorkoutSet",
			Handler:    _WorkoutService_LogWorkoutSet_Handler,
		},
		{
			MethodName: "GetCompletedExercises",
			Handler:    _WorkoutService_GetCompletedExercises_Handler,
		},
		{
			MethodName: "GetTrainingDays",
			Handler:    _WorkoutService_GetTrainingDays_Handler,
		},
		{
			MethodName: "GetWorkoutsForDay",
			Handler:    _WorkoutService_GetWorkoutsForDay_Handler,
		},
		{
			MethodName: "CreateTemplate",
			Handler:    _WorkoutService_CreateTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/workout/v1/workout.proto",
}
