syntax = "proto3";

package workout.v1;

option go_package = "github.com/PashakArt/go_lift_backend/api/proto/workout/v1;workoutv1";

import "google/protobuf/timestamp.proto";

service WorkoutService {
  // Инициализация
  rpc Init(InitRequest) returns (InitResponse);

  // Получение списка мышечных групп
  rpc GetMuscleGroups(GetMuscleGroupsRequest) returns (GetMuscleGroupsResponse);

  // Справочники упражнений
  rpc GetExercises(GetExercisesRequest) returns (GetExercisesResponse);

  // Старт тренировочной сессии
  rpc StartWorkoutSession(StartWorkoutSessionRequest) returns (StartWorkoutSessionResponse);

  // Завершение тренировочной сессии
  rpc FinishWorkoutSession(FinishWorkoutSessionRequest) returns (FinishWorkoutSessionResponse);

  // Сохранить/обновить выполненное упражнение
  rpc LogWorkoutSet(LogSetRequest) returns (LogSetResponse);

  // Получить список выполненных упражнений определенного вида в активной сессии
  rpc GetCompletedExercises(GetCompletedExercisesRequest) returns (GetCompletedExercisesResponse);

  // Получить список тренировочных дней
  rpc GetTrainingDays(GetTrainingDaysRequest) returns (GetTrainingDaysResponse);

  // Получить выполненные упражнения за день
  rpc GetWorkoutsForDay(GetWorkoutsForDayRequest) returns (GetWorkoutsForDayResponse);

  // Создание шаблона тренировки
  rpc CreateTemplate(CreateTemplateRequest) returns (CreateTemplateResponse);
}

message TargetSet {
  int32 set_num = 1;
  optional float weight = 2;
  optional int32 reps = 3;
  optional int32 duration_sec = 4;
  optional int32 distance_m = 5;
}

message TemplateItem {
  string exercise_id = 1;
  int32 order_index = 2;
  repeated TargetSet target_sets = 3;
}

message CreateTemplateRequest {
  string user_id = 1;
  string name = 2;
  repeated TemplateItem items = 3;
}

message CreateTemplateResponse {
  string template_id = 1;
}

message GetWorkoutsForDayRequest {
  string user_id = 1;
  string date = 2;
}

message GetWorkoutsForDayResponse {
  string date = 1;
  repeated WorkoutSessionDTO sessions = 2;
}

message WorkoutSessionDTO {
  string session_id = 1;
  string started_at = 2;
  string ended_at = 3;
  int64 duration_seconds = 4;
  repeated ExerciseDTO exercises = 5;
}

message ExerciseDTO {
  string exercise_id = 1;
  string name = 2;
  string type = 3;
  repeated CompletedSet sets = 4;
}


message GetTrainingDaysRequest {
  string userId = 1;
  int64 year = 2;
  int64 months = 3; // 1..12
}

message GetTrainingDaysResponse {
  repeated string training_days = 1;
}

message GetCompletedExercisesRequest {
  string user_id     = 1;
  string exercise_id = 2;
}

message CompletedSet {
  int32          set_number   = 1;
  string         set_id       = 2;
  optional float weight       = 3;
  optional int32 reps         = 4;
  optional int32 duration_sec = 5;
  optional int32 distance_m   = 6;
}

message GetCompletedExercisesResponse {
  repeated CompletedSet sets = 1;
}

message InitRequest {
  string tenant_id   = 1;
  string telegram_id = 2;
}

message TenantTheme {
  string mode             = 1;
  string text_color       = 2;
  string accent_color     = 3;
  string primary_color    = 4;
  string surface_color    = 5;
  string background_color = 6;

}

message TenantAssets {
  string logo_url = 1;
}

message TenantBranding {
  TenantTheme  theme  = 1;
  TenantAssets assets = 2;
}

message InitResponse {
  UserInfo                   user            = 1;
  bool                       is_new_user     = 2;
  optional ActiveSessionInfo active_session  = 3;
  TenantBranding             tenant_branding = 4;
}

message ActiveSessionInfo {
  string session_id = 1;
  string started_at = 2;
}

message UserInfo {
  string user_id     = 1;
  string tenant_id   = 2;
  string telegram_id = 3;
  string phone       = 4;
  string created_at  = 5;
}

enum ExerciseType {
  EXERCISE_TYPE_UNSPECIFIED = 0;
  EXERCISE_TYPE_DYNAMIC     = 1;     // Вес + Повторения
  EXERCISE_TYPE_STATIC      = 2;      // Время в секундах
  EXERCISE_TYPE_BODYWEIGHT  = 3;  // Только повторения
  EXERCISE_TYPE_CARDIO      = 4;      // Дистанция + Время
}

message GetExercisesRequest {
  string          muscle_group_id = 1;
  optional string user_id         = 2;
}

message ExerciseInfo {
  string                    exercise_id        = 1;
  string                    name               = 2;
  ExerciseType              type               = 3;
  bool                      is_global          = 4;
  repeated string           muscle_group_codes = 5;
  google.protobuf.Timestamp created_at         = 6;
}

message GetExercisesResponse {
  repeated ExerciseInfo exercises = 1;
}

// Режим выполнения тренировки (соответствует ENUM в БД)
enum SessionType {
  SESSION_TYPE_UNSPECIFIED = 0;
  SESSION_TYPE_CLASSIC     = 1;
  SESSION_TYPE_CIRCUIT     = 2;
}

message StartWorkoutSessionRequest {
  string          tenant_id   = 1;
  string          user_id     = 2;
  SessionType     type        = 3;
  optional string template_id = 4;
}

message FinishWorkoutSessionRequest {
  string user_id = 1;
}

message FinishWorkoutSessionResponse {

}

message StartWorkoutSessionResponse {
  string                    session_id = 1;
  string                    tenant_id  = 2;
  string                    user_id    = 3;
  SessionType               type       = 4;
  google.protobuf.Timestamp started_at = 5;
}

message GetMuscleGroupsRequest {

}

message GetMuscleGroupsResponse {
  repeated MuscleGroup muscle_groups = 1;
}

message MuscleGroup {
  string muscle_group_id = 1;
  string code            = 2;
  string name            = 3;
}

message LogSetRequest {
  string          session_id  = 1;
  string          exercise_id = 2;
  string          tenant_id   = 3;
  optional string set_id      = 4;

  // Метрики выполнения
  optional float weight       = 6;
  optional int32 reps         = 7;
  optional int32 duration_sec = 8;
  optional int32 distance_met = 9;
}

message LogSetResponse {
  string set_id     = 1;
  int32  set_number = 2;
}