// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/workout/v1/workout.proto

package workoutv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignInOrSignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TelegramId    string                 `protobuf:"bytes,2,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInOrSignUpRequest) Reset() {
	*x = SignInOrSignUpRequest{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInOrSignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInOrSignUpRequest) ProtoMessage() {}

func (x *SignInOrSignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInOrSignUpRequest.ProtoReflect.Descriptor instead.
func (*SignInOrSignUpRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{0}
}

func (x *SignInOrSignUpRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SignInOrSignUpRequest) GetTelegramId() string {
	if x != nil {
		return x.TelegramId
	}
	return ""
}

type SignInOrSignUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TelegramId    string                 `protobuf:"bytes,3,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInOrSignUpResponse) Reset() {
	*x = SignInOrSignUpResponse{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInOrSignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInOrSignUpResponse) ProtoMessage() {}

func (x *SignInOrSignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInOrSignUpResponse.ProtoReflect.Descriptor instead.
func (*SignInOrSignUpResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{1}
}

func (x *SignInOrSignUpResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SignInOrSignUpResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SignInOrSignUpResponse) GetTelegramId() string {
	if x != nil {
		return x.TelegramId
	}
	return ""
}

func (x *SignInOrSignUpResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SignInOrSignUpResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_api_proto_workout_v1_workout_proto protoreflect.FileDescriptor

const file_api_proto_workout_v1_workout_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/workout/v1/workout.proto\x12\n" +
	"workout.v1\"U\n" +
	"\x15SignInOrSignUpRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vtelegram_id\x18\x02 \x01(\tR\n" +
	"telegramId\"\xa4\x01\n" +
	"\x16SignInOrSignUpResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\vtelegram_id\x18\x03 \x01(\tR\n" +
	"telegramId\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt2i\n" +
	"\x0eWorkoutService\x12W\n" +
	"\x0eSignInOrSignup\x12!.workout.v1.SignInOrSignUpRequest\x1a\".workout.v1.SignInOrSignUpResponseBEZCgithub.com/PashakArt/go_lift_backend/api/proto/workout/v1;workoutv1b\x06proto3"

var (
	file_api_proto_workout_v1_workout_proto_rawDescOnce sync.Once
	file_api_proto_workout_v1_workout_proto_rawDescData []byte
)

func file_api_proto_workout_v1_workout_proto_rawDescGZIP() []byte {
	file_api_proto_workout_v1_workout_proto_rawDescOnce.Do(func() {
		file_api_proto_workout_v1_workout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_workout_v1_workout_proto_rawDesc), len(file_api_proto_workout_v1_workout_proto_rawDesc)))
	})
	return file_api_proto_workout_v1_workout_proto_rawDescData
}

var file_api_proto_workout_v1_workout_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_workout_v1_workout_proto_goTypes = []any{
	(*SignInOrSignUpRequest)(nil),  // 0: workout.v1.SignInOrSignUpRequest
	(*SignInOrSignUpResponse)(nil), // 1: workout.v1.SignInOrSignUpResponse
}
var file_api_proto_workout_v1_workout_proto_depIdxs = []int32{
	0, // 0: workout.v1.WorkoutService.SignInOrSignup:input_type -> workout.v1.SignInOrSignUpRequest
	1, // 1: workout.v1.WorkoutService.SignInOrSignup:output_type -> workout.v1.SignInOrSignUpResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_workout_v1_workout_proto_init() }
func file_api_proto_workout_v1_workout_proto_init() {
	if File_api_proto_workout_v1_workout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_workout_v1_workout_proto_rawDesc), len(file_api_proto_workout_v1_workout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_workout_v1_workout_proto_goTypes,
		DependencyIndexes: file_api_proto_workout_v1_workout_proto_depIdxs,
		MessageInfos:      file_api_proto_workout_v1_workout_proto_msgTypes,
	}.Build()
	File_api_proto_workout_v1_workout_proto = out.File
	file_api_proto_workout_v1_workout_proto_goTypes = nil
	file_api_proto_workout_v1_workout_proto_depIdxs = nil
}
