syntax = "proto3";

package workout.v1;

option go_package = "github.com/PashakArt/go_lift_backend/api/proto/workout/v1;workoutv1";

import "google/protobuf/timestamp.proto";

service WorkoutService {
  // Авторизация / Регистрация
  rpc SignInOrSignUp(SignInOrSignUpRequest) returns (SignInOrSignUpResponse);

  // Получение списка мышечных групп
  rpc GetMuscleGroups(GetMuscleGroupsRequest) returns (GetMuscleGroupsResponse);

  // Справочники упражнений
  rpc GetExercises(GetExercisesRequest) returns (GetExercisesResponse);

  // Старт тренировочной сессии
  rpc StartWorkoutSession(StartWorkoutSessionRequest) returns (StartWorkoutSessionResponse);
}

message SignInOrSignUpRequest {
  string tenant_id = 1;
  string telegram_id = 2;
}

message SignInOrSignUpResponse {
  UserInfo user = 1;
  bool is_new_user = 2;
  optional ActiveSessionInfo active_session = 3;
}

message ActiveSessionInfo {
  string session_id = 1;
  string started_at = 2;
}

message UserInfo {
  string user_id = 1;
  string tenant_id = 2;
  string telegram_id = 3;
  string phone = 4;
  string created_at = 5;
}

enum ExerciseType {
  EXERCISE_TYPE_UNSPECIFIED = 0;
  EXERCISE_TYPE_DYNAMIC = 1;     // Вес + Повторения
  EXERCISE_TYPE_STATIC = 2;      // Время в секундах
  EXERCISE_TYPE_BODYWEIGHT = 3;  // Только повторения
  EXERCISE_TYPE_CARDIO = 4;      // Дистанция + Время
}

message GetExercisesRequest {
  string muscle_group_id = 1;
  optional string user_id = 2;
}

message ExerciseInfo {
  string exercise_id = 1;
  string name = 2;
  ExerciseType type = 3;
  bool is_global = 4;
  repeated string muscle_group_codes = 5;
  google.protobuf.Timestamp created_at = 6;
}

message GetExercisesResponse {
  repeated ExerciseInfo exercises = 1;
}

// Режим выполнения тренировки (соответствует ENUM в БД)
enum SessionType {
  SESSION_TYPE_UNSPECIFIED = 0;
  SESSION_TYPE_CLASSIC = 1;
  SESSION_TYPE_CIRCUIT = 2;
}

message StartWorkoutSessionRequest {
  string tenant_id = 1;
  string user_id = 2;
  SessionType type = 3;
  optional string template_id = 4;
}

message StartWorkoutSessionResponse {
  string session_id = 1;
  string tenant_id = 2;
  string user_id = 3;
  SessionType type = 4;
  google.protobuf.Timestamp started_at = 5;
}

message GetMuscleGroupsRequest {
  
}

message GetMuscleGroupsResponse {
  repeated MuscleGroup muscle_groups = 1;
}

message MuscleGroup {
  string muscle_group_id = 1;
  string code = 2;
  string name = 3;
}