// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/workout/v1/workout.proto

package workoutv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExerciseType int32

const (
	ExerciseType_EXERCISE_TYPE_UNSPECIFIED ExerciseType = 0
	ExerciseType_EXERCISE_TYPE_DYNAMIC     ExerciseType = 1 // Вес + Повторения
	ExerciseType_EXERCISE_TYPE_STATIC      ExerciseType = 2 // Время в секундах
	ExerciseType_EXERCISE_TYPE_BODYWEIGHT  ExerciseType = 3 // Только повторения
	ExerciseType_EXERCISE_TYPE_CARDIO      ExerciseType = 4 // Дистанция + Время
)

// Enum value maps for ExerciseType.
var (
	ExerciseType_name = map[int32]string{
		0: "EXERCISE_TYPE_UNSPECIFIED",
		1: "EXERCISE_TYPE_DYNAMIC",
		2: "EXERCISE_TYPE_STATIC",
		3: "EXERCISE_TYPE_BODYWEIGHT",
		4: "EXERCISE_TYPE_CARDIO",
	}
	ExerciseType_value = map[string]int32{
		"EXERCISE_TYPE_UNSPECIFIED": 0,
		"EXERCISE_TYPE_DYNAMIC":     1,
		"EXERCISE_TYPE_STATIC":      2,
		"EXERCISE_TYPE_BODYWEIGHT":  3,
		"EXERCISE_TYPE_CARDIO":      4,
	}
)

func (x ExerciseType) Enum() *ExerciseType {
	p := new(ExerciseType)
	*p = x
	return p
}

func (x ExerciseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExerciseType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_workout_v1_workout_proto_enumTypes[0].Descriptor()
}

func (ExerciseType) Type() protoreflect.EnumType {
	return &file_api_proto_workout_v1_workout_proto_enumTypes[0]
}

func (x ExerciseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExerciseType.Descriptor instead.
func (ExerciseType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{0}
}

// Режим выполнения тренировки (соответствует ENUM в БД)
type SessionType int32

const (
	SessionType_SESSION_TYPE_UNSPECIFIED SessionType = 0
	SessionType_SESSION_TYPE_CLASSIC     SessionType = 1
	SessionType_SESSION_TYPE_CIRCUIT     SessionType = 2
)

// Enum value maps for SessionType.
var (
	SessionType_name = map[int32]string{
		0: "SESSION_TYPE_UNSPECIFIED",
		1: "SESSION_TYPE_CLASSIC",
		2: "SESSION_TYPE_CIRCUIT",
	}
	SessionType_value = map[string]int32{
		"SESSION_TYPE_UNSPECIFIED": 0,
		"SESSION_TYPE_CLASSIC":     1,
		"SESSION_TYPE_CIRCUIT":     2,
	}
)

func (x SessionType) Enum() *SessionType {
	p := new(SessionType)
	*p = x
	return p
}

func (x SessionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_workout_v1_workout_proto_enumTypes[1].Descriptor()
}

func (SessionType) Type() protoreflect.EnumType {
	return &file_api_proto_workout_v1_workout_proto_enumTypes[1]
}

func (x SessionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionType.Descriptor instead.
func (SessionType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{1}
}

type GetTrainingDaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Year          int64                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Months        int64                  `protobuf:"varint,3,opt,name=months,proto3" json:"months,omitempty"` // 1..12
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrainingDaysRequest) Reset() {
	*x = GetTrainingDaysRequest{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrainingDaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrainingDaysRequest) ProtoMessage() {}

func (x *GetTrainingDaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrainingDaysRequest.ProtoReflect.Descriptor instead.
func (*GetTrainingDaysRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{0}
}

func (x *GetTrainingDaysRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTrainingDaysRequest) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetTrainingDaysRequest) GetMonths() int64 {
	if x != nil {
		return x.Months
	}
	return 0
}

type GetTrainingDaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrainingDays  []string               `protobuf:"bytes,1,rep,name=training_days,json=trainingDays,proto3" json:"training_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrainingDaysResponse) Reset() {
	*x = GetTrainingDaysResponse{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrainingDaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrainingDaysResponse) ProtoMessage() {}

func (x *GetTrainingDaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrainingDaysResponse.ProtoReflect.Descriptor instead.
func (*GetTrainingDaysResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{1}
}

func (x *GetTrainingDaysResponse) GetTrainingDays() []string {
	if x != nil {
		return x.TrainingDays
	}
	return nil
}

type GetCompletedExercisesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExerciseId    string                 `protobuf:"bytes,2,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompletedExercisesRequest) Reset() {
	*x = GetCompletedExercisesRequest{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompletedExercisesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompletedExercisesRequest) ProtoMessage() {}

func (x *GetCompletedExercisesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompletedExercisesRequest.ProtoReflect.Descriptor instead.
func (*GetCompletedExercisesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{2}
}

func (x *GetCompletedExercisesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetCompletedExercisesRequest) GetExerciseId() string {
	if x != nil {
		return x.ExerciseId
	}
	return ""
}

type CompletedSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SetNumber     int32                  `protobuf:"varint,1,opt,name=set_number,json=setNumber,proto3" json:"set_number,omitempty"`
	SetId         string                 `protobuf:"bytes,2,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	Weight        *float32               `protobuf:"fixed32,3,opt,name=weight,proto3,oneof" json:"weight,omitempty"`
	Reps          *int32                 `protobuf:"varint,4,opt,name=reps,proto3,oneof" json:"reps,omitempty"`
	DurationSec   *int32                 `protobuf:"varint,5,opt,name=duration_sec,json=durationSec,proto3,oneof" json:"duration_sec,omitempty"`
	DistanceM     *int32                 `protobuf:"varint,6,opt,name=distance_m,json=distanceM,proto3,oneof" json:"distance_m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletedSet) Reset() {
	*x = CompletedSet{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletedSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletedSet) ProtoMessage() {}

func (x *CompletedSet) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletedSet.ProtoReflect.Descriptor instead.
func (*CompletedSet) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{3}
}

func (x *CompletedSet) GetSetNumber() int32 {
	if x != nil {
		return x.SetNumber
	}
	return 0
}

func (x *CompletedSet) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *CompletedSet) GetWeight() float32 {
	if x != nil && x.Weight != nil {
		return *x.Weight
	}
	return 0
}

func (x *CompletedSet) GetReps() int32 {
	if x != nil && x.Reps != nil {
		return *x.Reps
	}
	return 0
}

func (x *CompletedSet) GetDurationSec() int32 {
	if x != nil && x.DurationSec != nil {
		return *x.DurationSec
	}
	return 0
}

func (x *CompletedSet) GetDistanceM() int32 {
	if x != nil && x.DistanceM != nil {
		return *x.DistanceM
	}
	return 0
}

type GetCompletedExercisesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sets          []*CompletedSet        `protobuf:"bytes,1,rep,name=sets,proto3" json:"sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompletedExercisesResponse) Reset() {
	*x = GetCompletedExercisesResponse{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompletedExercisesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompletedExercisesResponse) ProtoMessage() {}

func (x *GetCompletedExercisesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompletedExercisesResponse.ProtoReflect.Descriptor instead.
func (*GetCompletedExercisesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{4}
}

func (x *GetCompletedExercisesResponse) GetSets() []*CompletedSet {
	if x != nil {
		return x.Sets
	}
	return nil
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TelegramId    string                 `protobuf:"bytes,2,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{5}
}

func (x *InitRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *InitRequest) GetTelegramId() string {
	if x != nil {
		return x.TelegramId
	}
	return ""
}

type TenantTheme struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Mode            string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	TextColor       string                 `protobuf:"bytes,2,opt,name=text_color,json=textColor,proto3" json:"text_color,omitempty"`
	AccentColor     string                 `protobuf:"bytes,3,opt,name=accent_color,json=accentColor,proto3" json:"accent_color,omitempty"`
	PrimaryColor    string                 `protobuf:"bytes,4,opt,name=primary_color,json=primaryColor,proto3" json:"primary_color,omitempty"`
	SurfaceColor    string                 `protobuf:"bytes,5,opt,name=surface_color,json=surfaceColor,proto3" json:"surface_color,omitempty"`
	BackgroundColor string                 `protobuf:"bytes,6,opt,name=background_color,json=backgroundColor,proto3" json:"background_color,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TenantTheme) Reset() {
	*x = TenantTheme{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantTheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantTheme) ProtoMessage() {}

func (x *TenantTheme) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantTheme.ProtoReflect.Descriptor instead.
func (*TenantTheme) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{6}
}

func (x *TenantTheme) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *TenantTheme) GetTextColor() string {
	if x != nil {
		return x.TextColor
	}
	return ""
}

func (x *TenantTheme) GetAccentColor() string {
	if x != nil {
		return x.AccentColor
	}
	return ""
}

func (x *TenantTheme) GetPrimaryColor() string {
	if x != nil {
		return x.PrimaryColor
	}
	return ""
}

func (x *TenantTheme) GetSurfaceColor() string {
	if x != nil {
		return x.SurfaceColor
	}
	return ""
}

func (x *TenantTheme) GetBackgroundColor() string {
	if x != nil {
		return x.BackgroundColor
	}
	return ""
}

type TenantAssets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogoUrl       string                 `protobuf:"bytes,1,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantAssets) Reset() {
	*x = TenantAssets{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantAssets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantAssets) ProtoMessage() {}

func (x *TenantAssets) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantAssets.ProtoReflect.Descriptor instead.
func (*TenantAssets) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{7}
}

func (x *TenantAssets) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

type TenantBranding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Theme         *TenantTheme           `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	Assets        *TenantAssets          `protobuf:"bytes,2,opt,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantBranding) Reset() {
	*x = TenantBranding{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantBranding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantBranding) ProtoMessage() {}

func (x *TenantBranding) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantBranding.ProtoReflect.Descriptor instead.
func (*TenantBranding) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{8}
}

func (x *TenantBranding) GetTheme() *TenantTheme {
	if x != nil {
		return x.Theme
	}
	return nil
}

func (x *TenantBranding) GetAssets() *TenantAssets {
	if x != nil {
		return x.Assets
	}
	return nil
}

type InitResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	User           *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	IsNewUser      bool                   `protobuf:"varint,2,opt,name=is_new_user,json=isNewUser,proto3" json:"is_new_user,omitempty"`
	ActiveSession  *ActiveSessionInfo     `protobuf:"bytes,3,opt,name=active_session,json=activeSession,proto3,oneof" json:"active_session,omitempty"`
	TenantBranding *TenantBranding        `protobuf:"bytes,4,opt,name=tenant_branding,json=tenantBranding,proto3" json:"tenant_branding,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{9}
}

func (x *InitResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *InitResponse) GetIsNewUser() bool {
	if x != nil {
		return x.IsNewUser
	}
	return false
}

func (x *InitResponse) GetActiveSession() *ActiveSessionInfo {
	if x != nil {
		return x.ActiveSession
	}
	return nil
}

func (x *InitResponse) GetTenantBranding() *TenantBranding {
	if x != nil {
		return x.TenantBranding
	}
	return nil
}

type ActiveSessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StartedAt     string                 `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveSessionInfo) Reset() {
	*x = ActiveSessionInfo{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveSessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveSessionInfo) ProtoMessage() {}

func (x *ActiveSessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveSessionInfo.ProtoReflect.Descriptor instead.
func (*ActiveSessionInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{10}
}

func (x *ActiveSessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ActiveSessionInfo) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TelegramId    string                 `protobuf:"bytes,3,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{11}
}

func (x *UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfo) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UserInfo) GetTelegramId() string {
	if x != nil {
		return x.TelegramId
	}
	return ""
}

func (x *UserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetExercisesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MuscleGroupId string                 `protobuf:"bytes,1,opt,name=muscle_group_id,json=muscleGroupId,proto3" json:"muscle_group_id,omitempty"`
	UserId        *string                `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExercisesRequest) Reset() {
	*x = GetExercisesRequest{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExercisesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExercisesRequest) ProtoMessage() {}

func (x *GetExercisesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExercisesRequest.ProtoReflect.Descriptor instead.
func (*GetExercisesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{12}
}

func (x *GetExercisesRequest) GetMuscleGroupId() string {
	if x != nil {
		return x.MuscleGroupId
	}
	return ""
}

func (x *GetExercisesRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type ExerciseInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExerciseId       string                 `protobuf:"bytes,1,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type             ExerciseType           `protobuf:"varint,3,opt,name=type,proto3,enum=workout.v1.ExerciseType" json:"type,omitempty"`
	IsGlobal         bool                   `protobuf:"varint,4,opt,name=is_global,json=isGlobal,proto3" json:"is_global,omitempty"`
	MuscleGroupCodes []string               `protobuf:"bytes,5,rep,name=muscle_group_codes,json=muscleGroupCodes,proto3" json:"muscle_group_codes,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExerciseInfo) Reset() {
	*x = ExerciseInfo{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseInfo) ProtoMessage() {}

func (x *ExerciseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseInfo.ProtoReflect.Descriptor instead.
func (*ExerciseInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{13}
}

func (x *ExerciseInfo) GetExerciseId() string {
	if x != nil {
		return x.ExerciseId
	}
	return ""
}

func (x *ExerciseInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExerciseInfo) GetType() ExerciseType {
	if x != nil {
		return x.Type
	}
	return ExerciseType_EXERCISE_TYPE_UNSPECIFIED
}

func (x *ExerciseInfo) GetIsGlobal() bool {
	if x != nil {
		return x.IsGlobal
	}
	return false
}

func (x *ExerciseInfo) GetMuscleGroupCodes() []string {
	if x != nil {
		return x.MuscleGroupCodes
	}
	return nil
}

func (x *ExerciseInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetExercisesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exercises     []*ExerciseInfo        `protobuf:"bytes,1,rep,name=exercises,proto3" json:"exercises,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExercisesResponse) Reset() {
	*x = GetExercisesResponse{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExercisesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExercisesResponse) ProtoMessage() {}

func (x *GetExercisesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExercisesResponse.ProtoReflect.Descriptor instead.
func (*GetExercisesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{14}
}

func (x *GetExercisesResponse) GetExercises() []*ExerciseInfo {
	if x != nil {
		return x.Exercises
	}
	return nil
}

type StartWorkoutSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          SessionType            `protobuf:"varint,3,opt,name=type,proto3,enum=workout.v1.SessionType" json:"type,omitempty"`
	TemplateId    *string                `protobuf:"bytes,4,opt,name=template_id,json=templateId,proto3,oneof" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkoutSessionRequest) Reset() {
	*x = StartWorkoutSessionRequest{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkoutSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkoutSessionRequest) ProtoMessage() {}

func (x *StartWorkoutSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkoutSessionRequest.ProtoReflect.Descriptor instead.
func (*StartWorkoutSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{15}
}

func (x *StartWorkoutSessionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *StartWorkoutSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StartWorkoutSessionRequest) GetType() SessionType {
	if x != nil {
		return x.Type
	}
	return SessionType_SESSION_TYPE_UNSPECIFIED
}

func (x *StartWorkoutSessionRequest) GetTemplateId() string {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return ""
}

type FinishWorkoutSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishWorkoutSessionRequest) Reset() {
	*x = FinishWorkoutSessionRequest{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishWorkoutSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishWorkoutSessionRequest) ProtoMessage() {}

func (x *FinishWorkoutSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishWorkoutSessionRequest.ProtoReflect.Descriptor instead.
func (*FinishWorkoutSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{16}
}

func (x *FinishWorkoutSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FinishWorkoutSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishWorkoutSessionResponse) Reset() {
	*x = FinishWorkoutSessionResponse{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishWorkoutSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishWorkoutSessionResponse) ProtoMessage() {}

func (x *FinishWorkoutSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishWorkoutSessionResponse.ProtoReflect.Descriptor instead.
func (*FinishWorkoutSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{17}
}

type StartWorkoutSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          SessionType            `protobuf:"varint,4,opt,name=type,proto3,enum=workout.v1.SessionType" json:"type,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkoutSessionResponse) Reset() {
	*x = StartWorkoutSessionResponse{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkoutSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkoutSessionResponse) ProtoMessage() {}

func (x *StartWorkoutSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkoutSessionResponse.ProtoReflect.Descriptor instead.
func (*StartWorkoutSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{18}
}

func (x *StartWorkoutSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartWorkoutSessionResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *StartWorkoutSessionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StartWorkoutSessionResponse) GetType() SessionType {
	if x != nil {
		return x.Type
	}
	return SessionType_SESSION_TYPE_UNSPECIFIED
}

func (x *StartWorkoutSessionResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

type GetMuscleGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMuscleGroupsRequest) Reset() {
	*x = GetMuscleGroupsRequest{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMuscleGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMuscleGroupsRequest) ProtoMessage() {}

func (x *GetMuscleGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMuscleGroupsRequest.ProtoReflect.Descriptor instead.
func (*GetMuscleGroupsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{19}
}

type GetMuscleGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MuscleGroups  []*MuscleGroup         `protobuf:"bytes,1,rep,name=muscle_groups,json=muscleGroups,proto3" json:"muscle_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMuscleGroupsResponse) Reset() {
	*x = GetMuscleGroupsResponse{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMuscleGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMuscleGroupsResponse) ProtoMessage() {}

func (x *GetMuscleGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMuscleGroupsResponse.ProtoReflect.Descriptor instead.
func (*GetMuscleGroupsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{20}
}

func (x *GetMuscleGroupsResponse) GetMuscleGroups() []*MuscleGroup {
	if x != nil {
		return x.MuscleGroups
	}
	return nil
}

type MuscleGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MuscleGroupId string                 `protobuf:"bytes,1,opt,name=muscle_group_id,json=muscleGroupId,proto3" json:"muscle_group_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuscleGroup) Reset() {
	*x = MuscleGroup{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuscleGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuscleGroup) ProtoMessage() {}

func (x *MuscleGroup) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuscleGroup.ProtoReflect.Descriptor instead.
func (*MuscleGroup) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{21}
}

func (x *MuscleGroup) GetMuscleGroupId() string {
	if x != nil {
		return x.MuscleGroupId
	}
	return ""
}

func (x *MuscleGroup) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MuscleGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LogSetRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SessionId  string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExerciseId string                 `protobuf:"bytes,2,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	TenantId   string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SetId      *string                `protobuf:"bytes,4,opt,name=set_id,json=setId,proto3,oneof" json:"set_id,omitempty"`
	// Метрики выполнения
	Weight        *float32 `protobuf:"fixed32,6,opt,name=weight,proto3,oneof" json:"weight,omitempty"`
	Reps          *int32   `protobuf:"varint,7,opt,name=reps,proto3,oneof" json:"reps,omitempty"`
	DurationSec   *int32   `protobuf:"varint,8,opt,name=duration_sec,json=durationSec,proto3,oneof" json:"duration_sec,omitempty"`
	DistanceMet   *int32   `protobuf:"varint,9,opt,name=distance_met,json=distanceMet,proto3,oneof" json:"distance_met,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogSetRequest) Reset() {
	*x = LogSetRequest{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSetRequest) ProtoMessage() {}

func (x *LogSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSetRequest.ProtoReflect.Descriptor instead.
func (*LogSetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{22}
}

func (x *LogSetRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LogSetRequest) GetExerciseId() string {
	if x != nil {
		return x.ExerciseId
	}
	return ""
}

func (x *LogSetRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *LogSetRequest) GetSetId() string {
	if x != nil && x.SetId != nil {
		return *x.SetId
	}
	return ""
}

func (x *LogSetRequest) GetWeight() float32 {
	if x != nil && x.Weight != nil {
		return *x.Weight
	}
	return 0
}

func (x *LogSetRequest) GetReps() int32 {
	if x != nil && x.Reps != nil {
		return *x.Reps
	}
	return 0
}

func (x *LogSetRequest) GetDurationSec() int32 {
	if x != nil && x.DurationSec != nil {
		return *x.DurationSec
	}
	return 0
}

func (x *LogSetRequest) GetDistanceMet() int32 {
	if x != nil && x.DistanceMet != nil {
		return *x.DistanceMet
	}
	return 0
}

type LogSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SetId         string                 `protobuf:"bytes,1,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	SetNumber     int32                  `protobuf:"varint,2,opt,name=set_number,json=setNumber,proto3" json:"set_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogSetResponse) Reset() {
	*x = LogSetResponse{}
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSetResponse) ProtoMessage() {}

func (x *LogSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workout_v1_workout_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSetResponse.ProtoReflect.Descriptor instead.
func (*LogSetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workout_v1_workout_proto_rawDescGZIP(), []int{23}
}

func (x *LogSetResponse) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *LogSetResponse) GetSetNumber() int32 {
	if x != nil {
		return x.SetNumber
	}
	return 0
}

var File_api_proto_workout_v1_workout_proto protoreflect.FileDescriptor

const file_api_proto_workout_v1_workout_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/workout/v1/workout.proto\x12\n" +
	"workout.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\\\n" +
	"\x16GetTrainingDaysRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x03R\x04year\x12\x16\n" +
	"\x06months\x18\x03 \x01(\x03R\x06months\">\n" +
	"\x17GetTrainingDaysResponse\x12#\n" +
	"\rtraining_days\x18\x01 \x03(\tR\ftrainingDays\"X\n" +
	"\x1cGetCompletedExercisesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vexercise_id\x18\x02 \x01(\tR\n" +
	"exerciseId\"\xfa\x01\n" +
	"\fCompletedSet\x12\x1d\n" +
	"\n" +
	"set_number\x18\x01 \x01(\x05R\tsetNumber\x12\x15\n" +
	"\x06set_id\x18\x02 \x01(\tR\x05setId\x12\x1b\n" +
	"\x06weight\x18\x03 \x01(\x02H\x00R\x06weight\x88\x01\x01\x12\x17\n" +
	"\x04reps\x18\x04 \x01(\x05H\x01R\x04reps\x88\x01\x01\x12&\n" +
	"\fduration_sec\x18\x05 \x01(\x05H\x02R\vdurationSec\x88\x01\x01\x12\"\n" +
	"\n" +
	"distance_m\x18\x06 \x01(\x05H\x03R\tdistanceM\x88\x01\x01B\t\n" +
	"\a_weightB\a\n" +
	"\x05_repsB\x0f\n" +
	"\r_duration_secB\r\n" +
	"\v_distance_m\"M\n" +
	"\x1dGetCompletedExercisesResponse\x12,\n" +
	"\x04sets\x18\x01 \x03(\v2\x18.workout.v1.CompletedSetR\x04sets\"K\n" +
	"\vInitRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vtelegram_id\x18\x02 \x01(\tR\n" +
	"telegramId\"\xd8\x01\n" +
	"\vTenantTheme\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x1d\n" +
	"\n" +
	"text_color\x18\x02 \x01(\tR\ttextColor\x12!\n" +
	"\faccent_color\x18\x03 \x01(\tR\vaccentColor\x12#\n" +
	"\rprimary_color\x18\x04 \x01(\tR\fprimaryColor\x12#\n" +
	"\rsurface_color\x18\x05 \x01(\tR\fsurfaceColor\x12)\n" +
	"\x10background_color\x18\x06 \x01(\tR\x0fbackgroundColor\")\n" +
	"\fTenantAssets\x12\x19\n" +
	"\blogo_url\x18\x01 \x01(\tR\alogoUrl\"q\n" +
	"\x0eTenantBranding\x12-\n" +
	"\x05theme\x18\x01 \x01(\v2\x17.workout.v1.TenantThemeR\x05theme\x120\n" +
	"\x06assets\x18\x02 \x01(\v2\x18.workout.v1.TenantAssetsR\x06assets\"\xfb\x01\n" +
	"\fInitResponse\x12(\n" +
	"\x04user\x18\x01 \x01(\v2\x14.workout.v1.UserInfoR\x04user\x12\x1e\n" +
	"\vis_new_user\x18\x02 \x01(\bR\tisNewUser\x12I\n" +
	"\x0eactive_session\x18\x03 \x01(\v2\x1d.workout.v1.ActiveSessionInfoH\x00R\ractiveSession\x88\x01\x01\x12C\n" +
	"\x0ftenant_branding\x18\x04 \x01(\v2\x1a.workout.v1.TenantBrandingR\x0etenantBrandingB\x11\n" +
	"\x0f_active_session\"Q\n" +
	"\x11ActiveSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"started_at\x18\x02 \x01(\tR\tstartedAt\"\x96\x01\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\vtelegram_id\x18\x03 \x01(\tR\n" +
	"telegramId\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"g\n" +
	"\x13GetExercisesRequest\x12&\n" +
	"\x0fmuscle_group_id\x18\x01 \x01(\tR\rmuscleGroupId\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\tH\x00R\x06userId\x88\x01\x01B\n" +
	"\n" +
	"\b_user_id\"\xf7\x01\n" +
	"\fExerciseInfo\x12\x1f\n" +
	"\vexercise_id\x18\x01 \x01(\tR\n" +
	"exerciseId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.workout.v1.ExerciseTypeR\x04type\x12\x1b\n" +
	"\tis_global\x18\x04 \x01(\bR\bisGlobal\x12,\n" +
	"\x12muscle_group_codes\x18\x05 \x03(\tR\x10muscleGroupCodes\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"N\n" +
	"\x14GetExercisesResponse\x126\n" +
	"\texercises\x18\x01 \x03(\v2\x18.workout.v1.ExerciseInfoR\texercises\"\xb5\x01\n" +
	"\x1aStartWorkoutSessionRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12+\n" +
	"\x04type\x18\x03 \x01(\x0e2\x17.workout.v1.SessionTypeR\x04type\x12$\n" +
	"\vtemplate_id\x18\x04 \x01(\tH\x00R\n" +
	"templateId\x88\x01\x01B\x0e\n" +
	"\f_template_id\"6\n" +
	"\x1bFinishWorkoutSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x1e\n" +
	"\x1cFinishWorkoutSessionResponse\"\xda\x01\n" +
	"\x1bStartWorkoutSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12+\n" +
	"\x04type\x18\x04 \x01(\x0e2\x17.workout.v1.SessionTypeR\x04type\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"\x18\n" +
	"\x16GetMuscleGroupsRequest\"W\n" +
	"\x17GetMuscleGroupsResponse\x12<\n" +
	"\rmuscle_groups\x18\x01 \x03(\v2\x17.workout.v1.MuscleGroupR\fmuscleGroups\"]\n" +
	"\vMuscleGroup\x12&\n" +
	"\x0fmuscle_group_id\x18\x01 \x01(\tR\rmuscleGroupId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xcf\x02\n" +
	"\rLogSetRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vexercise_id\x18\x02 \x01(\tR\n" +
	"exerciseId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x1a\n" +
	"\x06set_id\x18\x04 \x01(\tH\x00R\x05setId\x88\x01\x01\x12\x1b\n" +
	"\x06weight\x18\x06 \x01(\x02H\x01R\x06weight\x88\x01\x01\x12\x17\n" +
	"\x04reps\x18\a \x01(\x05H\x02R\x04reps\x88\x01\x01\x12&\n" +
	"\fduration_sec\x18\b \x01(\x05H\x03R\vdurationSec\x88\x01\x01\x12&\n" +
	"\fdistance_met\x18\t \x01(\x05H\x04R\vdistanceMet\x88\x01\x01B\t\n" +
	"\a_set_idB\t\n" +
	"\a_weightB\a\n" +
	"\x05_repsB\x0f\n" +
	"\r_duration_secB\x0f\n" +
	"\r_distance_met\"F\n" +
	"\x0eLogSetResponse\x12\x15\n" +
	"\x06set_id\x18\x01 \x01(\tR\x05setId\x12\x1d\n" +
	"\n" +
	"set_number\x18\x02 \x01(\x05R\tsetNumber*\x9a\x01\n" +
	"\fExerciseType\x12\x1d\n" +
	"\x19EXERCISE_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EXERCISE_TYPE_DYNAMIC\x10\x01\x12\x18\n" +
	"\x14EXERCISE_TYPE_STATIC\x10\x02\x12\x1c\n" +
	"\x18EXERCISE_TYPE_BODYWEIGHT\x10\x03\x12\x18\n" +
	"\x14EXERCISE_TYPE_CARDIO\x10\x04*_\n" +
	"\vSessionType\x12\x1c\n" +
	"\x18SESSION_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SESSION_TYPE_CLASSIC\x10\x01\x12\x18\n" +
	"\x14SESSION_TYPE_CIRCUIT\x10\x022\xdf\x05\n" +
	"\x0eWorkoutService\x129\n" +
	"\x04Init\x12\x17.workout.v1.InitRequest\x1a\x18.workout.v1.InitResponse\x12Z\n" +
	"\x0fGetMuscleGroups\x12\".workout.v1.GetMuscleGroupsRequest\x1a#.workout.v1.GetMuscleGroupsResponse\x12Q\n" +
	"\fGetExercises\x12\x1f.workout.v1.GetExercisesRequest\x1a .workout.v1.GetExercisesResponse\x12f\n" +
	"\x13StartWorkoutSession\x12&.workout.v1.StartWorkoutSessionRequest\x1a'.workout.v1.StartWorkoutSessionResponse\x12i\n" +
	"\x14FinishWorkoutSession\x12'.workout.v1.FinishWorkoutSessionRequest\x1a(.workout.v1.FinishWorkoutSessionResponse\x12F\n" +
	"\rLogWorkoutSet\x12\x19.workout.v1.LogSetRequest\x1a\x1a.workout.v1.LogSetResponse\x12l\n" +
	"\x15GetCompletedExercises\x12(.workout.v1.GetCompletedExercisesRequest\x1a).workout.v1.GetCompletedExercisesResponse\x12Z\n" +
	"\x0fGetTrainingDays\x12\".workout.v1.GetTrainingDaysRequest\x1a#.workout.v1.GetTrainingDaysResponseBEZCgithub.com/PashakArt/go_lift_backend/api/proto/workout/v1;workoutv1b\x06proto3"

var (
	file_api_proto_workout_v1_workout_proto_rawDescOnce sync.Once
	file_api_proto_workout_v1_workout_proto_rawDescData []byte
)

func file_api_proto_workout_v1_workout_proto_rawDescGZIP() []byte {
	file_api_proto_workout_v1_workout_proto_rawDescOnce.Do(func() {
		file_api_proto_workout_v1_workout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_workout_v1_workout_proto_rawDesc), len(file_api_proto_workout_v1_workout_proto_rawDesc)))
	})
	return file_api_proto_workout_v1_workout_proto_rawDescData
}

var file_api_proto_workout_v1_workout_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_workout_v1_workout_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_proto_workout_v1_workout_proto_goTypes = []any{
	(ExerciseType)(0),                     // 0: workout.v1.ExerciseType
	(SessionType)(0),                      // 1: workout.v1.SessionType
	(*GetTrainingDaysRequest)(nil),        // 2: workout.v1.GetTrainingDaysRequest
	(*GetTrainingDaysResponse)(nil),       // 3: workout.v1.GetTrainingDaysResponse
	(*GetCompletedExercisesRequest)(nil),  // 4: workout.v1.GetCompletedExercisesRequest
	(*CompletedSet)(nil),                  // 5: workout.v1.CompletedSet
	(*GetCompletedExercisesResponse)(nil), // 6: workout.v1.GetCompletedExercisesResponse
	(*InitRequest)(nil),                   // 7: workout.v1.InitRequest
	(*TenantTheme)(nil),                   // 8: workout.v1.TenantTheme
	(*TenantAssets)(nil),                  // 9: workout.v1.TenantAssets
	(*TenantBranding)(nil),                // 10: workout.v1.TenantBranding
	(*InitResponse)(nil),                  // 11: workout.v1.InitResponse
	(*ActiveSessionInfo)(nil),             // 12: workout.v1.ActiveSessionInfo
	(*UserInfo)(nil),                      // 13: workout.v1.UserInfo
	(*GetExercisesRequest)(nil),           // 14: workout.v1.GetExercisesRequest
	(*ExerciseInfo)(nil),                  // 15: workout.v1.ExerciseInfo
	(*GetExercisesResponse)(nil),          // 16: workout.v1.GetExercisesResponse
	(*StartWorkoutSessionRequest)(nil),    // 17: workout.v1.StartWorkoutSessionRequest
	(*FinishWorkoutSessionRequest)(nil),   // 18: workout.v1.FinishWorkoutSessionRequest
	(*FinishWorkoutSessionResponse)(nil),  // 19: workout.v1.FinishWorkoutSessionResponse
	(*StartWorkoutSessionResponse)(nil),   // 20: workout.v1.StartWorkoutSessionResponse
	(*GetMuscleGroupsRequest)(nil),        // 21: workout.v1.GetMuscleGroupsRequest
	(*GetMuscleGroupsResponse)(nil),       // 22: workout.v1.GetMuscleGroupsResponse
	(*MuscleGroup)(nil),                   // 23: workout.v1.MuscleGroup
	(*LogSetRequest)(nil),                 // 24: workout.v1.LogSetRequest
	(*LogSetResponse)(nil),                // 25: workout.v1.LogSetResponse
	(*timestamppb.Timestamp)(nil),         // 26: google.protobuf.Timestamp
}
var file_api_proto_workout_v1_workout_proto_depIdxs = []int32{
	5,  // 0: workout.v1.GetCompletedExercisesResponse.sets:type_name -> workout.v1.CompletedSet
	8,  // 1: workout.v1.TenantBranding.theme:type_name -> workout.v1.TenantTheme
	9,  // 2: workout.v1.TenantBranding.assets:type_name -> workout.v1.TenantAssets
	13, // 3: workout.v1.InitResponse.user:type_name -> workout.v1.UserInfo
	12, // 4: workout.v1.InitResponse.active_session:type_name -> workout.v1.ActiveSessionInfo
	10, // 5: workout.v1.InitResponse.tenant_branding:type_name -> workout.v1.TenantBranding
	0,  // 6: workout.v1.ExerciseInfo.type:type_name -> workout.v1.ExerciseType
	26, // 7: workout.v1.ExerciseInfo.created_at:type_name -> google.protobuf.Timestamp
	15, // 8: workout.v1.GetExercisesResponse.exercises:type_name -> workout.v1.ExerciseInfo
	1,  // 9: workout.v1.StartWorkoutSessionRequest.type:type_name -> workout.v1.SessionType
	1,  // 10: workout.v1.StartWorkoutSessionResponse.type:type_name -> workout.v1.SessionType
	26, // 11: workout.v1.StartWorkoutSessionResponse.started_at:type_name -> google.protobuf.Timestamp
	23, // 12: workout.v1.GetMuscleGroupsResponse.muscle_groups:type_name -> workout.v1.MuscleGroup
	7,  // 13: workout.v1.WorkoutService.Init:input_type -> workout.v1.InitRequest
	21, // 14: workout.v1.WorkoutService.GetMuscleGroups:input_type -> workout.v1.GetMuscleGroupsRequest
	14, // 15: workout.v1.WorkoutService.GetExercises:input_type -> workout.v1.GetExercisesRequest
	17, // 16: workout.v1.WorkoutService.StartWorkoutSession:input_type -> workout.v1.StartWorkoutSessionRequest
	18, // 17: workout.v1.WorkoutService.FinishWorkoutSession:input_type -> workout.v1.FinishWorkoutSessionRequest
	24, // 18: workout.v1.WorkoutService.LogWorkoutSet:input_type -> workout.v1.LogSetRequest
	4,  // 19: workout.v1.WorkoutService.GetCompletedExercises:input_type -> workout.v1.GetCompletedExercisesRequest
	2,  // 20: workout.v1.WorkoutService.GetTrainingDays:input_type -> workout.v1.GetTrainingDaysRequest
	11, // 21: workout.v1.WorkoutService.Init:output_type -> workout.v1.InitResponse
	22, // 22: workout.v1.WorkoutService.GetMuscleGroups:output_type -> workout.v1.GetMuscleGroupsResponse
	16, // 23: workout.v1.WorkoutService.GetExercises:output_type -> workout.v1.GetExercisesResponse
	20, // 24: workout.v1.WorkoutService.StartWorkoutSession:output_type -> workout.v1.StartWorkoutSessionResponse
	19, // 25: workout.v1.WorkoutService.FinishWorkoutSession:output_type -> workout.v1.FinishWorkoutSessionResponse
	25, // 26: workout.v1.WorkoutService.LogWorkoutSet:output_type -> workout.v1.LogSetResponse
	6,  // 27: workout.v1.WorkoutService.GetCompletedExercises:output_type -> workout.v1.GetCompletedExercisesResponse
	3,  // 28: workout.v1.WorkoutService.GetTrainingDays:output_type -> workout.v1.GetTrainingDaysResponse
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_proto_workout_v1_workout_proto_init() }
func file_api_proto_workout_v1_workout_proto_init() {
	if File_api_proto_workout_v1_workout_proto != nil {
		return
	}
	file_api_proto_workout_v1_workout_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_proto_workout_v1_workout_proto_msgTypes[9].OneofWrappers = []any{}
	file_api_proto_workout_v1_workout_proto_msgTypes[12].OneofWrappers = []any{}
	file_api_proto_workout_v1_workout_proto_msgTypes[15].OneofWrappers = []any{}
	file_api_proto_workout_v1_workout_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_workout_v1_workout_proto_rawDesc), len(file_api_proto_workout_v1_workout_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_workout_v1_workout_proto_goTypes,
		DependencyIndexes: file_api_proto_workout_v1_workout_proto_depIdxs,
		EnumInfos:         file_api_proto_workout_v1_workout_proto_enumTypes,
		MessageInfos:      file_api_proto_workout_v1_workout_proto_msgTypes,
	}.Build()
	File_api_proto_workout_v1_workout_proto = out.File
	file_api_proto_workout_v1_workout_proto_goTypes = nil
	file_api_proto_workout_v1_workout_proto_depIdxs = nil
}
