// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/proto/workout/v1/workout.proto

package workoutv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkoutService_SignInOrSignUp_FullMethodName      = "/workout.v1.WorkoutService/SignInOrSignUp"
	WorkoutService_GetExercises_FullMethodName        = "/workout.v1.WorkoutService/GetExercises"
	WorkoutService_StartWorkoutSession_FullMethodName = "/workout.v1.WorkoutService/StartWorkoutSession"
)

// WorkoutServiceClient is the client API for WorkoutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkoutServiceClient interface {
	// Авторизация / Регистрация
	SignInOrSignUp(ctx context.Context, in *SignInOrSignUpRequest, opts ...grpc.CallOption) (*SignInOrSignUpResponse, error)
	// Справочники упражнений
	GetExercises(ctx context.Context, in *GetExercisesRequest, opts ...grpc.CallOption) (*GetExercisesResponse, error)
	// Старт тренировочной сессии
	StartWorkoutSession(ctx context.Context, in *StartWorkoutSessionRequest, opts ...grpc.CallOption) (*StartWorkoutSessionResponse, error)
}

type workoutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkoutServiceClient(cc grpc.ClientConnInterface) WorkoutServiceClient {
	return &workoutServiceClient{cc}
}

func (c *workoutServiceClient) SignInOrSignUp(ctx context.Context, in *SignInOrSignUpRequest, opts ...grpc.CallOption) (*SignInOrSignUpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignInOrSignUpResponse)
	err := c.cc.Invoke(ctx, WorkoutService_SignInOrSignUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) GetExercises(ctx context.Context, in *GetExercisesRequest, opts ...grpc.CallOption) (*GetExercisesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExercisesResponse)
	err := c.cc.Invoke(ctx, WorkoutService_GetExercises_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) StartWorkoutSession(ctx context.Context, in *StartWorkoutSessionRequest, opts ...grpc.CallOption) (*StartWorkoutSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartWorkoutSessionResponse)
	err := c.cc.Invoke(ctx, WorkoutService_StartWorkoutSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkoutServiceServer is the server API for WorkoutService service.
// All implementations must embed UnimplementedWorkoutServiceServer
// for forward compatibility.
type WorkoutServiceServer interface {
	// Авторизация / Регистрация
	SignInOrSignUp(context.Context, *SignInOrSignUpRequest) (*SignInOrSignUpResponse, error)
	// Справочники упражнений
	GetExercises(context.Context, *GetExercisesRequest) (*GetExercisesResponse, error)
	// Старт тренировочной сессии
	StartWorkoutSession(context.Context, *StartWorkoutSessionRequest) (*StartWorkoutSessionResponse, error)
	mustEmbedUnimplementedWorkoutServiceServer()
}

// UnimplementedWorkoutServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkoutServiceServer struct{}

func (UnimplementedWorkoutServiceServer) SignInOrSignUp(context.Context, *SignInOrSignUpRequest) (*SignInOrSignUpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignInOrSignUp not implemented")
}
func (UnimplementedWorkoutServiceServer) GetExercises(context.Context, *GetExercisesRequest) (*GetExercisesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExercises not implemented")
}
func (UnimplementedWorkoutServiceServer) StartWorkoutSession(context.Context, *StartWorkoutSessionRequest) (*StartWorkoutSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartWorkoutSession not implemented")
}
func (UnimplementedWorkoutServiceServer) mustEmbedUnimplementedWorkoutServiceServer() {}
func (UnimplementedWorkoutServiceServer) testEmbeddedByValue()                        {}

// UnsafeWorkoutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkoutServiceServer will
// result in compilation errors.
type UnsafeWorkoutServiceServer interface {
	mustEmbedUnimplementedWorkoutServiceServer()
}

func RegisterWorkoutServiceServer(s grpc.ServiceRegistrar, srv WorkoutServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkoutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkoutService_ServiceDesc, srv)
}

func _WorkoutService_SignInOrSignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInOrSignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).SignInOrSignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_SignInOrSignUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).SignInOrSignUp(ctx, req.(*SignInOrSignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_GetExercises_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExercisesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).GetExercises(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_GetExercises_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).GetExercises(ctx, req.(*GetExercisesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_StartWorkoutSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWorkoutSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).StartWorkoutSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_StartWorkoutSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).StartWorkoutSession(ctx, req.(*StartWorkoutSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkoutService_ServiceDesc is the grpc.ServiceDesc for WorkoutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkoutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workout.v1.WorkoutService",
	HandlerType: (*WorkoutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignInOrSignUp",
			Handler:    _WorkoutService_SignInOrSignUp_Handler,
		},
		{
			MethodName: "GetExercises",
			Handler:    _WorkoutService_GetExercises_Handler,
		},
		{
			MethodName: "StartWorkoutSession",
			Handler:    _WorkoutService_StartWorkoutSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/workout/v1/workout.proto",
}
