// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/analytics/v1/analytics.proto

package analyticsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricType int32

const (
	MetricType_METRIC_TYPE_UNSPECIFIED MetricType = 0
	// DYNAMIC
	MetricType_METRIC_TYPE_MAX_WEIGHT MetricType = 1
	MetricType_METRIC_TYPE_MAX_REPS   MetricType = 2
	MetricType_METRIC_TYPE_VOLUME     MetricType = 3
	// BODYWEIGHT
	MetricType_METRIC_TYPE_BODYWEIGHT_MAX_REPS MetricType = 4
	// Общее количество повторений всех подходов за тренировочную сессию.
	MetricType_METRIC_TYPE_TOTAL_REPS MetricType = 5
	// Максимальный дополнительный вес за тренировочную сессию.
	// Например: +10, +15, +20 -> значение = 20.
	MetricType_METRIC_TYPE_MAX_ADDED_WEIGHT MetricType = 6
	// Сумма additional_weight * reps по подходам,
	// где дополнительный вес задан.
	// Например:
	// +20 x 8
	// +20 x 8
	// +15 x 10
	// = 470 кг дополнительного веса.
	MetricType_METRIC_TYPE_ADDED_WEIGHT_VOLUME MetricType = 7
	// Максимальная продолжительность одного подхода
	// за тренировочную сессию.
	MetricType_METRIC_TYPE_MAX_DURATION   MetricType = 8
	MetricType_METRIC_TYPE_TOTAL_DURATION MetricType = 9
	// CARDIO
	MetricType_METRIC_TYPE_DISTANCE MetricType = 10
	MetricType_METRIC_TYPE_DURATION MetricType = 11
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0:  "METRIC_TYPE_UNSPECIFIED",
		1:  "METRIC_TYPE_MAX_WEIGHT",
		2:  "METRIC_TYPE_MAX_REPS",
		3:  "METRIC_TYPE_VOLUME",
		4:  "METRIC_TYPE_BODYWEIGHT_MAX_REPS",
		5:  "METRIC_TYPE_TOTAL_REPS",
		6:  "METRIC_TYPE_MAX_ADDED_WEIGHT",
		7:  "METRIC_TYPE_ADDED_WEIGHT_VOLUME",
		8:  "METRIC_TYPE_MAX_DURATION",
		9:  "METRIC_TYPE_TOTAL_DURATION",
		10: "METRIC_TYPE_DISTANCE",
		11: "METRIC_TYPE_DURATION",
	}
	MetricType_value = map[string]int32{
		"METRIC_TYPE_UNSPECIFIED":         0,
		"METRIC_TYPE_MAX_WEIGHT":          1,
		"METRIC_TYPE_MAX_REPS":            2,
		"METRIC_TYPE_VOLUME":              3,
		"METRIC_TYPE_BODYWEIGHT_MAX_REPS": 4,
		"METRIC_TYPE_TOTAL_REPS":          5,
		"METRIC_TYPE_MAX_ADDED_WEIGHT":    6,
		"METRIC_TYPE_ADDED_WEIGHT_VOLUME": 7,
		"METRIC_TYPE_MAX_DURATION":        8,
		"METRIC_TYPE_TOTAL_DURATION":      9,
		"METRIC_TYPE_DISTANCE":            10,
		"METRIC_TYPE_DURATION":            11,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_analytics_v1_analytics_proto_enumTypes[0].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_api_proto_analytics_v1_analytics_proto_enumTypes[0]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_analytics_v1_analytics_proto_rawDescGZIP(), []int{0}
}

type GetExerciseAnalyticsRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ExerciseId string                 `protobuf:"bytes,1,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	// Начало периода.
	// Если не передано — с момента первого выполнения упражнения.
	From *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// Конец периода.
	// Если не передано — до текущего момента.
	To            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExerciseAnalyticsRequest) Reset() {
	*x = GetExerciseAnalyticsRequest{}
	mi := &file_api_proto_analytics_v1_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExerciseAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExerciseAnalyticsRequest) ProtoMessage() {}

func (x *GetExerciseAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_v1_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExerciseAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*GetExerciseAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_v1_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetExerciseAnalyticsRequest) GetExerciseId() string {
	if x != nil {
		return x.ExerciseId
	}
	return ""
}

func (x *GetExerciseAnalyticsRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetExerciseAnalyticsRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type GetExerciseAnalyticsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Metrics         []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	PersonalRecords *PersonalRecords       `protobuf:"bytes,2,opt,name=personal_records,json=personalRecords,proto3" json:"personal_records,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetExerciseAnalyticsResponse) Reset() {
	*x = GetExerciseAnalyticsResponse{}
	mi := &file_api_proto_analytics_v1_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExerciseAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExerciseAnalyticsResponse) ProtoMessage() {}

func (x *GetExerciseAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_v1_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExerciseAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*GetExerciseAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_v1_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *GetExerciseAnalyticsResponse) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *GetExerciseAnalyticsResponse) GetPersonalRecords() *PersonalRecords {
	if x != nil {
		return x.PersonalRecords
	}
	return nil
}

type Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  MetricType             `protobuf:"varint,1,opt,name=type,proto3,enum=analytics.v1.MetricType" json:"type,omitempty"`
	// Одна точка = одна тренировочная сессия.
	Points        []*DataPoint `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_api_proto_analytics_v1_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_v1_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_v1_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *Metric) GetType() MetricType {
	if x != nil {
		return x.Type
	}
	return MetricType_METRIC_TYPE_UNSPECIFIED
}

func (x *Metric) GetPoints() []*DataPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type DataPoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Время начала тренировочной сессии.
	SessionStartTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=session_start_time,json=sessionStartTime,proto3" json:"session_start_time,omitempty"`
	// Значение метрики в данной тренировочной сессии.
	Value         float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	SessionId     string  `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	mi := &file_api_proto_analytics_v1_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_v1_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_v1_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *DataPoint) GetSessionStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SessionStartTime
	}
	return nil
}

func (x *DataPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DataPoint) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type PersonalRecords struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MaxWeight      *Record                `protobuf:"bytes,1,opt,name=max_weight,json=maxWeight,proto3,oneof" json:"max_weight,omitempty"`
	MaxReps        *Record                `protobuf:"bytes,2,opt,name=max_reps,json=maxReps,proto3,oneof" json:"max_reps,omitempty"`
	Volume         *Record                `protobuf:"bytes,3,opt,name=volume,proto3,oneof" json:"volume,omitempty"`
	MaxAddedWeight *Record                `protobuf:"bytes,4,opt,name=max_added_weight,json=maxAddedWeight,proto3,oneof" json:"max_added_weight,omitempty"`
	TotalReps      *Record                `protobuf:"bytes,5,opt,name=total_reps,json=totalReps,proto3,oneof" json:"total_reps,omitempty"`
	MaxDuration    *Record                `protobuf:"bytes,6,opt,name=max_duration,json=maxDuration,proto3,oneof" json:"max_duration,omitempty"`
	MaxDistance    *Record                `protobuf:"bytes,7,opt,name=max_distance,json=maxDistance,proto3,oneof" json:"max_distance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PersonalRecords) Reset() {
	*x = PersonalRecords{}
	mi := &file_api_proto_analytics_v1_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalRecords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalRecords) ProtoMessage() {}

func (x *PersonalRecords) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_v1_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalRecords.ProtoReflect.Descriptor instead.
func (*PersonalRecords) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_v1_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *PersonalRecords) GetMaxWeight() *Record {
	if x != nil {
		return x.MaxWeight
	}
	return nil
}

func (x *PersonalRecords) GetMaxReps() *Record {
	if x != nil {
		return x.MaxReps
	}
	return nil
}

func (x *PersonalRecords) GetVolume() *Record {
	if x != nil {
		return x.Volume
	}
	return nil
}

func (x *PersonalRecords) GetMaxAddedWeight() *Record {
	if x != nil {
		return x.MaxAddedWeight
	}
	return nil
}

func (x *PersonalRecords) GetTotalReps() *Record {
	if x != nil {
		return x.TotalReps
	}
	return nil
}

func (x *PersonalRecords) GetMaxDuration() *Record {
	if x != nil {
		return x.MaxDuration
	}
	return nil
}

func (x *PersonalRecords) GetMaxDistance() *Record {
	if x != nil {
		return x.MaxDistance
	}
	return nil
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AchievedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=achieved_at,json=achievedAt,proto3" json:"achieved_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_api_proto_analytics_v1_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_v1_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_v1_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *Record) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Record) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Record) GetAchievedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AchievedAt
	}
	return nil
}

var File_api_proto_analytics_v1_analytics_proto protoreflect.FileDescriptor

const file_api_proto_analytics_v1_analytics_proto_rawDesc = "" +
	"\n" +
	"&api/proto/analytics/v1/analytics.proto\x12\fanalytics.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x01\n" +
	"\x1bGetExerciseAnalyticsRequest\x12\x1f\n" +
	"\vexercise_id\x18\x01 \x01(\tR\n" +
	"exerciseId\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\"\x98\x01\n" +
	"\x1cGetExerciseAnalyticsResponse\x12.\n" +
	"\ametrics\x18\x01 \x03(\v2\x14.analytics.v1.MetricR\ametrics\x12H\n" +
	"\x10personal_records\x18\x02 \x01(\v2\x1d.analytics.v1.PersonalRecordsR\x0fpersonalRecords\"g\n" +
	"\x06Metric\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.analytics.v1.MetricTypeR\x04type\x12/\n" +
	"\x06points\x18\x02 \x03(\v2\x17.analytics.v1.DataPointR\x06points\"\x8a\x01\n" +
	"\tDataPoint\x12H\n" +
	"\x12session_start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x10sessionStartTime\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\x9c\x04\n" +
	"\x0fPersonalRecords\x128\n" +
	"\n" +
	"max_weight\x18\x01 \x01(\v2\x14.analytics.v1.RecordH\x00R\tmaxWeight\x88\x01\x01\x124\n" +
	"\bmax_reps\x18\x02 \x01(\v2\x14.analytics.v1.RecordH\x01R\amaxReps\x88\x01\x01\x121\n" +
	"\x06volume\x18\x03 \x01(\v2\x14.analytics.v1.RecordH\x02R\x06volume\x88\x01\x01\x12C\n" +
	"\x10max_added_weight\x18\x04 \x01(\v2\x14.analytics.v1.RecordH\x03R\x0emaxAddedWeight\x88\x01\x01\x128\n" +
	"\n" +
	"total_reps\x18\x05 \x01(\v2\x14.analytics.v1.RecordH\x04R\ttotalReps\x88\x01\x01\x12<\n" +
	"\fmax_duration\x18\x06 \x01(\v2\x14.analytics.v1.RecordH\x05R\vmaxDuration\x88\x01\x01\x12<\n" +
	"\fmax_distance\x18\a \x01(\v2\x14.analytics.v1.RecordH\x06R\vmaxDistance\x88\x01\x01B\r\n" +
	"\v_max_weightB\v\n" +
	"\t_max_repsB\t\n" +
	"\a_volumeB\x13\n" +
	"\x11_max_added_weightB\r\n" +
	"\v_total_repsB\x0f\n" +
	"\r_max_durationB\x0f\n" +
	"\r_max_distance\"z\n" +
	"\x06Record\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12;\n" +
	"\vachieved_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"achievedAt*\xf1\x02\n" +
	"\n" +
	"MetricType\x12\x1b\n" +
	"\x17METRIC_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16METRIC_TYPE_MAX_WEIGHT\x10\x01\x12\x18\n" +
	"\x14METRIC_TYPE_MAX_REPS\x10\x02\x12\x16\n" +
	"\x12METRIC_TYPE_VOLUME\x10\x03\x12#\n" +
	"\x1fMETRIC_TYPE_BODYWEIGHT_MAX_REPS\x10\x04\x12\x1a\n" +
	"\x16METRIC_TYPE_TOTAL_REPS\x10\x05\x12 \n" +
	"\x1cMETRIC_TYPE_MAX_ADDED_WEIGHT\x10\x06\x12#\n" +
	"\x1fMETRIC_TYPE_ADDED_WEIGHT_VOLUME\x10\a\x12\x1c\n" +
	"\x18METRIC_TYPE_MAX_DURATION\x10\b\x12\x1e\n" +
	"\x1aMETRIC_TYPE_TOTAL_DURATION\x10\t\x12\x18\n" +
	"\x14METRIC_TYPE_DISTANCE\x10\n" +
	"\x12\x18\n" +
	"\x14METRIC_TYPE_DURATION\x10\v2\x81\x01\n" +
	"\x10AnalyticsService\x12m\n" +
	"\x14GetExerciseAnalytics\x12).analytics.v1.GetExerciseAnalyticsRequest\x1a*.analytics.v1.GetExerciseAnalyticsResponseBIZGgithub.com/PashakArt/go_lift_backend/api/proto/analytics/v1;analyticsv1b\x06proto3"

var (
	file_api_proto_analytics_v1_analytics_proto_rawDescOnce sync.Once
	file_api_proto_analytics_v1_analytics_proto_rawDescData []byte
)

func file_api_proto_analytics_v1_analytics_proto_rawDescGZIP() []byte {
	file_api_proto_analytics_v1_analytics_proto_rawDescOnce.Do(func() {
		file_api_proto_analytics_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_analytics_v1_analytics_proto_rawDesc), len(file_api_proto_analytics_v1_analytics_proto_rawDesc)))
	})
	return file_api_proto_analytics_v1_analytics_proto_rawDescData
}

var file_api_proto_analytics_v1_analytics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_analytics_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_analytics_v1_analytics_proto_goTypes = []any{
	(MetricType)(0),                      // 0: analytics.v1.MetricType
	(*GetExerciseAnalyticsRequest)(nil),  // 1: analytics.v1.GetExerciseAnalyticsRequest
	(*GetExerciseAnalyticsResponse)(nil), // 2: analytics.v1.GetExerciseAnalyticsResponse
	(*Metric)(nil),                       // 3: analytics.v1.Metric
	(*DataPoint)(nil),                    // 4: analytics.v1.DataPoint
	(*PersonalRecords)(nil),              // 5: analytics.v1.PersonalRecords
	(*Record)(nil),                       // 6: analytics.v1.Record
	(*timestamppb.Timestamp)(nil),        // 7: google.protobuf.Timestamp
}
var file_api_proto_analytics_v1_analytics_proto_depIdxs = []int32{
	7,  // 0: analytics.v1.GetExerciseAnalyticsRequest.from:type_name -> google.protobuf.Timestamp
	7,  // 1: analytics.v1.GetExerciseAnalyticsRequest.to:type_name -> google.protobuf.Timestamp
	3,  // 2: analytics.v1.GetExerciseAnalyticsResponse.metrics:type_name -> analytics.v1.Metric
	5,  // 3: analytics.v1.GetExerciseAnalyticsResponse.personal_records:type_name -> analytics.v1.PersonalRecords
	0,  // 4: analytics.v1.Metric.type:type_name -> analytics.v1.MetricType
	4,  // 5: analytics.v1.Metric.points:type_name -> analytics.v1.DataPoint
	7,  // 6: analytics.v1.DataPoint.session_start_time:type_name -> google.protobuf.Timestamp
	6,  // 7: analytics.v1.PersonalRecords.max_weight:type_name -> analytics.v1.Record
	6,  // 8: analytics.v1.PersonalRecords.max_reps:type_name -> analytics.v1.Record
	6,  // 9: analytics.v1.PersonalRecords.volume:type_name -> analytics.v1.Record
	6,  // 10: analytics.v1.PersonalRecords.max_added_weight:type_name -> analytics.v1.Record
	6,  // 11: analytics.v1.PersonalRecords.total_reps:type_name -> analytics.v1.Record
	6,  // 12: analytics.v1.PersonalRecords.max_duration:type_name -> analytics.v1.Record
	6,  // 13: analytics.v1.PersonalRecords.max_distance:type_name -> analytics.v1.Record
	7,  // 14: analytics.v1.Record.achieved_at:type_name -> google.protobuf.Timestamp
	1,  // 15: analytics.v1.AnalyticsService.GetExerciseAnalytics:input_type -> analytics.v1.GetExerciseAnalyticsRequest
	2,  // 16: analytics.v1.AnalyticsService.GetExerciseAnalytics:output_type -> analytics.v1.GetExerciseAnalyticsResponse
	16, // [16:17] is the sub-list for method output_type
	15, // [15:16] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_proto_analytics_v1_analytics_proto_init() }
func file_api_proto_analytics_v1_analytics_proto_init() {
	if File_api_proto_analytics_v1_analytics_proto != nil {
		return
	}
	file_api_proto_analytics_v1_analytics_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_analytics_v1_analytics_proto_rawDesc), len(file_api_proto_analytics_v1_analytics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_analytics_v1_analytics_proto_goTypes,
		DependencyIndexes: file_api_proto_analytics_v1_analytics_proto_depIdxs,
		EnumInfos:         file_api_proto_analytics_v1_analytics_proto_enumTypes,
		MessageInfos:      file_api_proto_analytics_v1_analytics_proto_msgTypes,
	}.Build()
	File_api_proto_analytics_v1_analytics_proto = out.File
	file_api_proto_analytics_v1_analytics_proto_goTypes = nil
	file_api_proto_analytics_v1_analytics_proto_depIdxs = nil
}
